version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-post-service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: post-service
    volumes:
      - ./data/mongodb:/data/db
