name: CI/CD Pipeline with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./post-service

    # - name: SonarCloud Scan
    #   run: mvn sonar:sonar -Dsonar.projectKey=Moh-Bouali_post-service -Dsonar.organization=moh-bouali -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    #   working-directory: ./post-service

    - name: SonarCloud Scan
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=Moh-Bouali_post-service\
          -Dsonar.organization=moh-bouali \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      working-directory: ./post-service

    - name: Build Docker Image
      run: docker build -t moh96/post-service:latest -t moh96/post-service:${{ github.sha }} .
      working-directory: ./post-service

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.43.0_Linux-64bit.deb
      
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Cache Trivy Vulnerability Database
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: ${{ runner.os }}-trivy-java-db
        restore-keys: |
          ${{ runner.os }}-trivy-java-db

    # - name: Scan Docker Image
    #   run: trivy image --exit-code 1 --severity CRITICAL moh96/post-service:latest

    - name: Scan Docker Image
      run: |
        for i in {1..3}; do
          trivy image --exit-code 1 --severity CRITICAL moh96/post-service:latest && break || sleep 60;
        done

    - name: Push Docker Image with SHA Tag
      run: docker push moh96/post-service:${{ github.sha }}

    - name: Push Docker Image with Latest Tag
      run: docker push moh96/post-service:latest

    # - name: Deploy to Kubernetes
    #   run: kubectl apply -f kubernetes-deployment.yaml
    #   working-directory: ./post-service
